// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"crm-service-go/app/clients"
	"crm-service-go/app/controllers"
	"crm-service-go/app/controllers/inside"
	"crm-service-go/app/repositories"
	"crm-service-go/app/services"
	"crm-service-go/app/services/inside"
	"crm-service-go/server"
)

// Injectors from wire.go:

func initServer() *server.Server {
	repository := repositories.NewRepository()
	httpClient := clients.NewHttpClient()
	service := services.NewService(repository, httpClient)
	controller := controllers.NewController(repository, service)
	insideService := service_inside.NewInsideService(service)
	insideController := controller_inside.NewInsideController(service, insideService)
	serverServer := server.NewServer(controller, insideController)
	return serverServer
}
